Created branch lesson-2. Installed Node.js and Prettier.
KateRadziukevich/if-html pull request #1
Opened 2022-07-07 15:41 UTC by KateRadziukevich

node_modules/ add in .gitignore
Created directory about and created a file index.html
In the file index.html wrote a text about why you chose the direction of Front-end development and used various tags

2022-07-07 16:24 UTC, 5tronciy commented on .gitignore
> +node_modules
node_modules and node_modules/ are almost the same.

2022-07-07 18:13 UTC, 5tronciy commented on index.html
> +    <a href="./about">Об авторе</a>
wrong path

2022-07-07 18:18 UTC, 5tronciy commented on about/index.html
> +    </blockquote>
bad style: open and close tags should be on the same level.

2022-07-07 18:27 UTC, 5tronciy commented on about/index.html
> +      <em>„Здесь я хочу рассказать о своих золотых правилах. Первое: обращайся с другими так, как ты хочешь, чтобы они обращались с тобой. Следуя этому правилу, в любой ситуации будешь знать, что дел
Too long string, don't forget to use prettier.

2022-07-07 18:30 UTC, 5tronciy requested changes
Added some comments in rows

2022-07-08 15:08 UTC, 5tronciy commented
You should make changes before requesting new review.

2022-07-11 22:03 UTC, 5tronciy commented
Looks better. But why did you fix not all remarks?

2022-07-12 10:07 UTC, KateRadziukevich commented on .gitignore
> +node_modules
I do not know what to do with the remark

2022-07-13 19:50 UTC, 5tronciy commented on .gitignore
> +node_modules
Read the task, pls.

2022-07-13 19:50 UTC, 5tronciy commented on index.html
> +    <a href="./about">Об авторе</a>
Does it work in your browser?

2022-07-14 17:36 UTC, KateRadziukevich commented on index.html
> +    <a href="./about">Об авторе</a>
Yes

2022-07-14 20:54 UTC, 5tronciy commented on index.html
> +    <a href="./about">Об авторе</a>
I checked it in Chrome and Safari - it is not what you expected. Websites are for people, not only for you.

2022-07-21 21:53 UTC, merged